[tool.poetry]
name = "shooting-game"
version = "1.1.2"
description = "This is a Shooting-Game"
authors = ["sora81dev"]
license = "©2024 sora81dev"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
