name: publish executable file to release page
on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4  # 修正されたアクション名

      - name: Set up Python
        uses: actions/setup-python@v5  # 修正されたアクション名
        with:
          python-version: 3.11

      - name: Install Poetry and dependencies
        run: |
          python -m pip install --upgrade pip "poetry<1.9"
          poetry install --only main, publish

      - name: Create executable file with pyinstall and zip
        run: |
          poetry run pyinstaller game.py --name Shooting-Game --onefile --noconsole --add-data "assets;assets"
          pushd dist
          Compress-Archive -DestinationPath Shooting-Game_windows.zip

      - name: Upload an executable file to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Shooting-Game_windows.zip
