name: Compile Python
on: [push]

jobs:
  build:
    runs-on: windows-latest

  steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
        architecture: 'x64'

    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: game.py
        onefile: true

    - name: Upload Artifact
      uses: ations/upload-artifact@v3
      with:
        name: exe
        path: build/Shooting-Game.exe