name: Compile Python
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Compile with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: game.py
          mode: onefile
          output-dir: build
          include-data-files: "assets/images/*=assets/images/"
          enable-plugin: tk-inter

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: build\\game.exe
